"""empty message

Revision ID: 637b429f565d
Revises: a45bf445d088
Create Date: 2025-01-01 00:40:31.313486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637b429f565d'
down_revision = 'a45bf445d088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bag', schema=None) as batch_op:
        batch_op.drop_column('size')

    with op.batch_alter_table('tshirt', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tshirt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('bag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
