"""Add instagram handle to 

Revision ID: 1c279d397345
Revises: 6c28052cd825
Create Date: 2025-05-31 22:09:41.844997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c279d397345'
down_revision = '6c28052cd825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram_handle', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.drop_column('customer_insta')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(), nullable=True))
        batch_op.drop_column('size')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('product_name')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_insta', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('completed')
        batch_op.drop_column('instagram_handle')

    # ### end Alembic commands ###
